server:
  port: 7003
  error:
    include-message: always

spring:
  application:
    name: job
  datasource:
    url: jdbc:postgresql://localhost/job
    username: ${DB_USERNAME:postgres}
    password: ${DB_PWD:postgres}

logging:
  level:
    root: info
    ru.rsh12: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
