server:
  port: 7002
  error:
    include-message: always

spring:
  application:
    name: resume
  datasource:
    url: jdbc:postgresql://localhost/resume
    username: ${DB_USERNAME}
    password: ${DB_PWD}

logging:
  level:
    root: info
    ru.rsh12: debug
