server:
  port: 7002
  error:
    include-message: always

spring:
  application:
    name: resume
  datasource:
    url: jdbc:postgresql://localhost/resume
    username: ${DB_USERNAME:postgres}
    password: ${DB_PWD:postgres}

logging:
  level:
    root: info
    ru.rsh12: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
