server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: company
  datasource:
    url: jdbc:postgresql://localhost/company
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  data:
    web:
      pageable:
        max-page-size: 500

logging:
  level:
    root: info
    ru.rsh12: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace