server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: company
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/company
    username: ${DB_USERNAME}
    password: ${DB_PWD}

logging:
  level:
    root: info
    ru.rsh12: debug