server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: company
  datasource:
    url: jdbc:postgresql://localhost/company
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  flyway:
    locations: classpath:db.migration

logging:
  level:
    root: info
    ru.rsh12: debug