spring.config.import: "configserver:"

spring:
  application:
    name: company
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      uri: http://localhost:8888
      username: ${CONFIG_SERVER_USR:usr}
      password: ${CONFIG_SERVER_PWD:pwd}

---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    config:
      uri: http://config-server:8888
