{{- define "common.istio_base" -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: composite-require-jwt
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app.kubernetes.io/name: composite
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: composite-request-authentication
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: http://192.168.49.2:9999/auth/realms/ugk
    jwksUri: http://192.168.49.2:9999/auth/realms/ugk/protocol/openid-connect/certs
  selector:
    matchLabels:
      app.kubernetes.io/name: composite
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hands-on-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - minikube.me
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: hands-on-certificate
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hands-on-vs
spec:
  gateways:
  - hands-on-gw
  hosts:
  - minikube.me
  http:
  - match:
    - uri:
        prefix: /api/v1/composite
    route:
    - destination:
        host: composite
        port:
          number: 80
  - match:
    - uri:
        prefix: /api/v1/openapi
    route:
    - destination:
        host: composite
        port:
          number: 80
  - match:
    - uri:
        prefix: /api/v1/webjars
    route:
    - destination:
        host: composite
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: health-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - health.minikube.me
    port:
      number: 443
      name: https-health
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: hands-on-certificate
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: health-vs
spec:
  hosts:
  - health.minikube.me
  gateways:
  - health-gateway
  http:
  - route:
    - destination:
        host: composite
        port:
          number: 4004
{{- end -}}
