app:
  auth-server: localhost
  config-server: localhost
  http-pattern: "/api/v1/composite"
  scope-companies: "SCOPE_companies"
  scope-vacancies: "SCOPE_vacancies"
  scope-resumes: "SCOPE_resumes"

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0 # send all trace to Zipkin


spring.cloud.stream.default-binder: rabbit

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: "*"

# Readiness probes
management.endpoint.health.probes.enabled: true
management.endpoint.health.group.readiness.include: rabbit, db

# Graceful shutdown with a wait period
server.shutdown: "graceful"
spring.lifecycle.timeout-per-shutdown-phase: "10s"


---
spring.config.activate.on-profile: docker

spring.rabbitmq.host: rabbitmq

app:
  config-server: config-server
  auth-server: keycloak

---
spring.config.activate.on-profile: kuber
app:
  auth-server: 172.17.0.1

---
spring.config.activate.on-profile: prod
spring.rabbitmq.host: 172.17.0.1

app:
  auth-server: 172.17.0.1

# Only allow management endpoints over http in production for info, health and circuitbreakerevents
management.endpoints.web.exposure.include: health,info,circuitbreakerevents