app:
  auth-server: localhost
  config-server: localhost
  eureka-server: localhost
  eureka-username: u
  eureka-password: p
  http-pattern: "/api/v1/composite"
  scope-companies: "SCOPE_companies"
  scope-vacancies: "SCOPE_vacancies"
  scope-resumes: "SCOPE_resumes"

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0 # send all trace to Zipkin


spring.cloud.stream.default-binder: rabbit

management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: "*"


---
spring.config.activate.on-profile: docker

spring.rabbitmq.host: rabbitmq

app:
  eureka-server: eureka
  config-server: config-server
  auth-server: keycloak
