server:
  port: 7000
  error:
    include-message: always

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  cache.disabled: true
  packages-to-scan: ru.rsh12
  paths-to-match: /**

  swagger-ui:
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: admins-client
      clientSecret: u86HYlNxFFZ7GzJeTacgTCFYjROuFhZA # temporary secret key
      use-basic-authentication-with-access-code-grant: true
  oAuthFlow:
    authorizationUrl: http://localhost:9999/auth/realms/ugk/protocol/openid-connect/auth
    tokenUrl: http://localhost:9999/auth/realms/ugk/protocol/openid-connect/token
#    refreshUrl: some_refresh_url

server.forward-headers-strategy: framework

spring:
  application:
    name: composite
  cloud:
    stream:
      bindings:
        companies-out-0:
          destination: companies
          producer:
            required-groups: auditGroup
        resumes-out-0:
          destination: resumes
          producer:
            required-groups: auditGroup
        jobs-out-0:
          destination: jobs
          producer:
            required-groups: auditGroup
      default-binder: rabbit

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.auth-server}:9999/auth/realms/ugk

logging:
  level:
    root: info
    ru.rsh12: debug
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

resilience4j:
  retry:
    configs:
      shared:
        max-attempts: 3
        wait-duration: 1500
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.InternalServerError
    instances:
      company:
        base-config: shared

  timelimiter:
    configs:
      shared:
        timeout-duration: 3s
    instances:
      company:
        base-config: shared

  circuitbreaker:
    configs:
      shared:
        allow-health-indicator-to-fail: false
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - ru.rsh12.api.exceptions.NotFoundException
          - ru.rsh12.api.exceptions.InvalidInputException
    instances:
      company:
        base-config: shared

management:
  health:
    circuitbreakers:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: warn
    ru.rsh12: warn
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: warn