server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-alias: localhost

spring:
  sleuth:
    reactor:
      instrumentation-type: decorate_on_last # enable Sleuth to track trace IDs correctly

  cloud:
    gateway:
      routes:
        - id: composite
          uri: http://composite
          predicates:
            - Path=/api/v1/composite/**

        - id: auth-server
          uri: http://${app.auth-server}:9999
          predicates:
            - Path=/oauth2/{segment}
          filters:
            - SetPath=/auth/realms/ugk/protocol/openid-connect/{segment}

        - id: config-server
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config(?<segment>/?.*), $\{segment}

        - id: composite-swagger-ui
          uri: http://composite
          predicates:
            - Path=/openapi/**

        - id: composite-swagger-ui-webjars
          uri: http://composite
          predicates:
            - Path=/webjars/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.auth-server}:9999/auth/realms/ugk

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: trace