server:
  port: 7003
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost/job
    hikari:
      initialization-fail-timeout: 60000
  data:
    web:
      pageable:
        max-page-size: 500
  cloud:
    function:
      definition: jobPostMessageProcessor
    stream:
      default-binder: rabbit
      bindings:
        jobPostMessageProcessor-in-0:
          destination: jobs
          group: jobsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          jobPostMessageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true

logging:
  level:
    root: info
    ru.rsh12: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


---
spring:
  datasource:
    url: jdbc:postgresql://postgres/job
  config:
    activate:
      on-profile: docker

server:
  port: 80

---
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/job
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: info
    ru.rsh12: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info