secrets:

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit-user-prod
    SPRING_RABBITMQ_PASSWORD: rabbit-pwd-prod

  rabbitmq-zipkin-credentials:
    RABBIT_USER: rabbit-user-prod
    RABBIT_PASSWORD: rabbit-pwd-prod

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres-user-dev
    SPRING_DATASOURCE_PASSWORD: postgres-pwd-dev

gateway:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

company:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

resume:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

job:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

composite:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

zipkin-server:
  env:
    LOGGING_LEVEL_ROOT: WARN
    RABBIT_ADDRESSES: 172.17.0.1
  envFromSecretRefs:
    - rabbitmq-zipkin-credentials
  resources:
    requests:
      memory: 300Mi
    limits:
      memory: 600Mi