secrets:

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit
    SPRING_RABBITMQ_PASSWORD: rabbit

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: postgres

company:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

resume:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

job:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

composite:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  envFromSecretRefs:
    - rabbitmq-credentials
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi
