secrets:

  rabbitmq-server-credentials:
    RABBITMQ_DEFAULT_USER: rabbit
    RABBITMQ_DEFAULT_PASS: rabbit

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit
    SPRING_RABBITMQ_PASSWORD: rabbit

  postgres-server-credentials:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: postgres

rabbitmq:
  envFromSecretRefs:
    - rabbitmq-server-credentials

postgres:
  envFromSecretRefs:
    - postgres-server-credentials

company:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

job:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

resume:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

composite:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

destinationRules:
  - name: composite
  - name: company
  - name: resume
  - name: job