secrets:

  rabbitmq-server-credentials:
    RABBITMQ_DEFAULT_USER: rabbit-user-dev
    RABBITMQ_DEFAULT_PASS: rabbit-user-dev

  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit-user-dev
    SPRING_RABBITMQ_PASSWORD: rabbit-pwd-dev

  rabbitmq-zipkin-credentials:
    RABBIT_USER: rabbit-user-dev
    RABBIT_PASSWORD: rabbit-pwd-dev

  postgres-server-credentials:
    POSTGRES_USER: postgres-user-dev
    POSTGRES_PASSWORD: postgres-pwd-dev
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres-user-dev
    SPRING_DATASOURCE_PASSWORD: postgres-pwd-dev

postgres:
  envFromSecretRefs:
    - postgres-server-credentials

company:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

job:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

resume:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

composite:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials

zipkin-server:
  envFromSecretRefs:
    - rabbitmq-zipkin-credentials