version: '3.8'

services:

  postgres:
    image: postgres:14-alpine
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ../datastore/keycloak:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      PGDATA: /var/lib/postgresql/data/pgdata

  keycloak:
    image: jboss/keycloak
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PWD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PWD}
    command: [ "-Djboss.http.port=9999" ]
    ports:
      - "9999:9999"
    depends_on:
      postgres:
        condition: service_started

