version: '3.8'

services:

  job:
    build: ../microservices/job-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_started

  resume:
    build: ../microservices/resume-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_started

  company:
    build: ../microservices/company-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_started

  composite:
    build: ../microservices/composite-service
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3.8.11-management-alpine
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 60

  postgres:
    image: postgres:14-alpine
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./datastore/pg_data_local:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: on-failure

  eureka:
    build: ../spring-cloud/eureka-server
    deploy:
      resources:
        limits:
          memory: 512M

  gateway:
    build: ../spring-cloud/gateway
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8433:8433"