version: '3.8'

services:

  postgres:
    image: postgres:14
    container_name: keycloak-postgres
    volumes:
      - ./datastore/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata

  keycloak:
    image: jboss/keycloak
    container_name: keycloak-app
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started

