version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: on-failure
