INSERT INTO business_stream(name)
VALUES ('Transportation, Logistics, Warehousing, International Logistics'),
       ('IT, System Integration, Internet'),
       ('Electronics, Tool Engineering, Household Appliances, Computers and Office Equipment'),
       ('Telecommunications, Communications'),
       ('Media, Marketing, Advertising, PR, Design, Production'),
       ('Construction, Real Estate, Architecture'),
       ('Automotive Business'),
       ('Timber Industry'),
       ('Metallurgy, Metalwork'),
       ('Food Products'),
       ('Agriculture'),
       ('Heavy Engineering'),
       ('Chemical Production, Fertilizers'),
       ('Government Organizations'),
       ('Public Activity, Political Parties, Volunteering, Non-Profit Organizations'),
       ('Educational Institutions'),
       ('Retail'),
       ('FMCG (non-edible)'),
       ('Financial Sector'),
       ('Business Services'),
       ('Mining Industry'),
       ('Power Industry'),
       ('Oil and Gas'),
       ('Medicine, Pharmaceuticals, Pharmacies'),
       ('Public Services'),
       ('Hotels, Restaurants, Food Service Industry, Catering'),
       ('Utilities'),
       ('Art, Culture'),
       ('Industrial Equipment, Machine Tools and Components'),
       ('Multiprofile Asset Management');
