fullnameOverride: composite

image:
  name: composite-service

env:
  SPRING_PROFILES_ACTIVE: "docker,kuber"
  SPRING_CONFIG_LOCATION: file:/config-repo/application.yml,file:/config-repo/composite.yml

livenessProbe_enabled: true

readinessProbe_enabled: true

configmap:
  enabled: true
  volumeMounts:
    mountPath: /config-repo